export const addtocart ="ADD_T0_CART"
export const removefromcart ="REMOVE_FROM_CART"
export const emptycart ="EMPTY_CART"
export const productdata ="PRODUCT_DATA"
export const setdata = "SET_DATA"
